services:
  db:
    image: postgres:17
    command: ["postgres", "-c", "log_statement=all"]
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=local_password
      - POSTGRES_DB=app
    ports:
      - 5432:5432

  backend:
    build: ./backend
    ports:
      - "8888:8888"
    volumes:
      - ./backend:/app
