"""add campaign and the relationship

Revision ID: a3f62beb6100
Revises: 06fd5a448fe9
Create Date: 2025-05-25 19:28:56.180856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3f62beb6100'
down_revision: Union[str, None] = '06fd5a448fe9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaign',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('insights', sa.Text(), nullable=True),
    sa.Column('recommendations', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('ad', sa.Column('campaign_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'ad', 'campaign', ['campaign_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ad', type_='foreignkey')
    op.drop_column('ad', 'campaign_id')
    op.drop_table('campaign')
    # ### end Alembic commands ###
